# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scientists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=128)),
                ('extra_info', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('scientists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientists.Scientists')),
            ],
        ),
    ]
