# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='scientists',
            new_name='scientist',
        ),
    ]
