# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0002_auto_20170310_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='scientist',
        ),
        migrations.DeleteModel(
            name='Scientists',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
