# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0003_auto_20170310_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='men_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scientist',
            name='women_number',
            field=models.IntegerField(default=0),
        ),
    ]
